apiVersion: v1
kind: Service
metadata:
 name: sample-cluster
 labels:
   app: sample-cluster
spec:
 type: ClusterIP
 ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
 selector:
   app: sample

   